Import Required Libraries

In [2]:
import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis

import requests

!conda install -c anaconda beautifulsoup4 --y 

!conda install lxml --y

from bs4 import BeautifulSoup

print ("done")

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - beautifulsoup4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.1.1   |                0         132 KB  anaconda
    certifi-2020.4.5.1         |           py36_0         159 KB  anaconda
    ------------------------------------------------------------
                                           Total:         291 KB

The following packages will be UPDATED:

  openssl            conda-forge::openssl-1.1.1f-h516909a_0 --> anaconda::openssl-1.1.1-h7b6447c_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.4.5~ --> anaconda::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2020.4.5.1-py36h~ --> anaconda::certifi-2020.4.5.1-py36_0



Downloading and Extracting Packages
certifi-2020.4.5.1   | 159 KB    | ##################################### | 100%
ca-certificates-2020 | 132 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - lxml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.1.1   |                0         125 KB
    certifi-2020.4.5.1         |           py36_0         155 KB
    ------------------------------------------------------------
                                           Total:         280 KB

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates                                  anaconda --> pkgs/main
  certifi                                          anaconda --> pkgs/main
  openssl                anaconda::openssl-1.1.1-h7b6447c_0 --> pkgs/main::openssl-1.1.1f-h7b6447c_0



Downloading and Extracting Packages
ca-certificates-2020 | 125 KB    | ##################################### | 100%
certifi-2020.4.5.1   | 155 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
done

Downloads the file and converts to table using BeautifulSoup

In [3]:
source = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text



soup = BeautifulSoup(source,"lxml")

table = soup.find('table')

Converts the html table into dataframe and removes Not assigned postal codes

In [4]:
df = pd.read_html(str(table))[0]
new_df = df[df.Borough != 'Not assigned'].reset_index(drop= True)



new_df.loc[new_df['Neighborhood'] == 'Not assigned', ['Neighborhood']] = new_df['Borough']

new_df = new_df.groupby(['Postal code','Borough'])['Neighborhood'].apply(','.join).reset_index()
new_df.rename(columns={"Postal code": "Postcode"}, inplace = True)
new_df

    Postcode      Borough                                       Neighborhood
0        M1B  Scarborough                                    Malvern / Rouge
1        M1C  Scarborough           Rouge Hill / Port Union / Highland Creek
2        M1E  Scarborough                Guildwood / Morningside / West Hill
3        M1G  Scarborough                                             Woburn
4        M1H  Scarborough                                          Cedarbrae
..       ...          ...                                                ...
98       M9N         York                                             Weston
99       M9P    Etobicoke                                          Westmount
100      M9R    Etobicoke  Kingsview Village / St. Phillips / Martin Grov...
101      M9V    Etobicoke  South Steeles / Silverstone / Humbergate / Jam...
102      M9W    Etobicoke                                          Northwest

[103 rows x 3 columns]

In [5]:
new_df.shape

(103, 3)

In [6]:
df1 = pd.read_csv('http://cocl.us/Geospatial_data')
df1.rename(columns={"Postal Code": "Postcode"}, inplace = True)
df1

    Postcode   Latitude  Longitude
0        M1B  43.806686 -79.194353
1        M1C  43.784535 -79.160497
2        M1E  43.763573 -79.188711
3        M1G  43.770992 -79.216917
4        M1H  43.773136 -79.239476
..       ...        ...        ...
98       M9N  43.706876 -79.518188
99       M9P  43.696319 -79.532242
100      M9R  43.688905 -79.554724
101      M9V  43.739416 -79.588437
102      M9W  43.706748 -79.594054

[103 rows x 3 columns]

Merging the two DFs

In [7]:
df3 = pd.merge (new_df,df1)
df3

,Postcode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,Malvern / Rouge,43.806686,-79.194353
1,M1C,Scarborough,Rouge Hill / Port Union / Highland Creek,43.784535,-79.160497
2,M1E,Scarborough,Guildwood / Morningside / West Hill,43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,Kingsview Village / St. Phillips / Martin Grov...,43.688905,-79.554724
101,M9V,Etobicoke,South Steeles / Silverstone / Humbergate / Jam...,43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054